### ISSUE TITLE
Crashes everytime  when reaching hosted.owntracks.org

### ISSUE THREAD

**Issue by tiptronic** [ckrey/MQTTInspector#62] opened 2015-09-16 13:52 UTC
-Launch MQTTInspector
-Create a new session: (fill in with your user/pass from hosted.owntracks.org)
----
host: hosted.owntracks.org
SUB: owntracks/#  
---
-keep everything else as is...
-slide the slider at 'Auth' to on

Now when I connect it crashes:  iPhone6 / iOS 9.0 GM  (will try later using a iOS 8.4.x)

**Comment by jpmens** [comment] 2015-09-16 14:23
Please note Hosted user is "<username>|<devicename>" (vertical bar) and password is "<token>" for that device.

**Comment by tiptronic** [comment] 2015-09-16 14:33
Great info... ;)

But still crashes:

Sep 16 16:26:24 AndyPhone6 MQTTInspector[1821] <Warning>: connectionClosed
Sep 16 16:26:24 AndyPhone6 MQTTInspector[1821] <Error>: *** Terminating app due to uncaught exception 'UIViewControllerHierarchyInconsistency', reason: 'A view can only be associated with at most one view controller at a time! View <UITableView: 0x15e8e5c00; frame = (0 65; 96 275); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x15e6c7410>; layer = <CALayer: 0x15f82ea10>; contentOffset: {0, 0}; contentSize: {96, 0}> is associated with <UITableViewController: 0x15e5c65a0>. Clear this association before associating this view with <UITableViewController: 0x15e7920c0>.'
	*** First throw call stack:
	(0x182738f5c 0x197327f80 0x182738ea4 0x187d0c74c 0x187d0c5c8 0x187d0c258 0x187ec9454 0x1000c7e40 0x1000e5d9c 0x1000e5b4c 0x1000e3584 0x1000dd8e8 0x18268dd04 0x18268dc20 0x1826f05a4 0x1826f0038 0x1826edd38 0x18261cdc0 0x18d770088 0x187cf6f60 0x1000d7fb8 0x197b528b8)
Sep 16 16:26:24 AndyPhone6 SpringBoard[61] <Warning>: HW kbd: Failed to set (null) as keyboard focus
Sep 16 16:26:24 AndyPhone6 com.apple.xpc.launchd[1] (UIKitApplication:org.mqttitude.MQTTInspector[0x7341][1821]) <Notice>: Service exited due to signal: Abort trap: 6
Sep 16 16:26:24 AndyPhone6 SpringBoard[61] <Warning>: Application 'UIKitApplication:org.mqttitude.MQTTInspector[0x7341]' crashed.
Sep 16 16:26:24 AndyPhone6 UserEventAgent[26] <Warning>: 4553722395393: id=org.mqttitude.MQTTInspector pid=1821, state=0
Sep 16 16:26:24 AndyPhone6 diagnosticd[92] <Error>: unable to find offset 0x97b47a5c in shared cache for arch 'arm64'
Sep 16 16:26:24 AndyPhone6 ReportCrash[1826] <Notice>: platform_thread_get_unique_id matched 949198
Sep 16 16:26:24 AndyPhone6 ReportCrash[1826] <Notice>: Formulating report for corpse[1821] MQTTInspector
Sep 16 16:26:24 AndyPhone6 ReportCrash[1826] <Warning>: saved type '109_MQTTInspector' report (1 of max 25) as /var/mobile/Library/Logs/CrashReporter/MQTTInspector_2015-09-16-162624_AndyPhone6.ips
Sep 16 16:26:26 AndyPhone6 k

**Comment by jpmens** [comment] 2015-09-16 14:47
Cannot reproduce with Inspector 1.6 on iOS 8.

```
Protocol level: 4
TLS: true
Port: 8883
Auth: true
username: as above
password: <token>
```

**Comment by tiptronic** [comment] 2015-09-16 15:08
Using these setting it works - if just one of those doesn't match it immediately crashes...
Now running on iOS 8.4.1 and iOS 9

thx

**Comment by jpmens** [comment] 2015-09-16 15:27
What you describes sounds as though as soon as CONNACK != 0, the crash occurs.
@ckrey will look at it when he's back.

**Comment by ckrey** [comment] 2015-09-19 10:19
fixed in 1.7

**Comment by tiptronic** [comment] 2015-09-19 12:04
Do you commit that somewhen soon, or do you have a Testflight?

**Comment by ckrey** [comment] 2015-09-19 12:58
as soon as German Telekom gets my VDSL running

**Comment by tiptronic** [comment] 2015-09-19 13:42
good luck with that :+1:

**Closed** 2015-09-24 11:25 UTC
Labels: bug, fixed
